name: colored_json
description: A package that converts JSON string into a customizable flutter widget.
version: 1.1.0
homepage: https://github.com/Manty-K/colored_json

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

screenshots:
  - description: Default View
    path: screenshots/01-screenshot.jpeg
  - description: Custimised View
    path: screenshots/02-screenshot.jpeg
  - description: Colored JSON Widget 3
    path: screenshots/03-screenshot.jpeg

flutter:
